"""baseline schema

Revision ID: f0ff6f61408d
Revises: 
Create Date: 2026-07-31 17:37:31.973842
"""

# ruff: noqa: E501

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f0ff6f61408d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=220), nullable=True),
    sa.Column('password_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_access', sa.Boolean(), nullable=False),
    sa.Column('access_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_version', sa.String(length=32), nullable=True),
    sa.Column('offer_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_accepted_ip', sa.String(length=64), nullable=True),
    sa.Column('offer_accepted_user_agent', sa.Text(), nullable=True),
    sa.Column('onboarding_tour_available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_tour_dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_access_expires_at'), 'accounts', ['access_expires_at'], unique=False)
    op.create_index(op.f('ix_accounts_locked_until'), 'accounts', ['locked_until'], unique=False)
    op.create_index(op.f('ix_accounts_paid_access'), 'accounts', ['paid_access'], unique=False)
    op.create_index(op.f('ix_accounts_phone'), 'accounts', ['phone'], unique=True)
    op.create_index(op.f('ix_accounts_telegram_user_id'), 'accounts', ['telegram_user_id'], unique=True)
    op.create_index(op.f('ix_accounts_trial_expires_at'), 'accounts', ['trial_expires_at'], unique=False)
    op.create_table('auction_lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_lot_id', sa.String(length=64), nullable=False),
    sa.Column('source_search_status', sa.String(length=64), nullable=True),
    sa.Column('auction_number', sa.String(length=32), nullable=True),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('auction_type', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=160), nullable=True),
    sa.Column('district', sa.String(length=160), nullable=True),
    sa.Column('locality', sa.String(length=160), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('cadastre_number', sa.String(length=64), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('land_rights', sa.String(length=240), nullable=True),
    sa.Column('functional_purpose_level2', sa.String(length=240), nullable=True),
    sa.Column('functional_purpose_level3', sa.String(length=320), nullable=True),
    sa.Column('functional_purpose_level4', sa.String(length=320), nullable=True),
    sa.Column('use_goal', sa.String(length=160), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('start_price_kzt', sa.Float(), nullable=True),
    sa.Column('guarantee_kzt', sa.Float(), nullable=True),
    sa.Column('sale_price_kzt', sa.Float(), nullable=True),
    sa.Column('auction_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('seller_name', sa.Text(), nullable=True),
    sa.Column('seller_bin', sa.String(length=16), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_object_url', sa.Text(), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_lot_id', name='uq_auction_lot_source_id')
    )
    op.create_index(op.f('ix_auction_lots_active'), 'auction_lots', ['active'], unique=False)
    op.create_index(op.f('ix_auction_lots_area_ha'), 'auction_lots', ['area_ha'], unique=False)
    op.create_index(op.f('ix_auction_lots_auction_number'), 'auction_lots', ['auction_number'], unique=False)
    op.create_index(op.f('ix_auction_lots_auction_starts_at'), 'auction_lots', ['auction_starts_at'], unique=False)
    op.create_index(op.f('ix_auction_lots_cadastre_number'), 'auction_lots', ['cadastre_number'], unique=False)
    op.create_index(op.f('ix_auction_lots_district'), 'auction_lots', ['district'], unique=False)
    op.create_index(op.f('ix_auction_lots_functional_purpose_level2'), 'auction_lots', ['functional_purpose_level2'], unique=False)
    op.create_index(op.f('ix_auction_lots_last_seen_at'), 'auction_lots', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_auction_lots_object_type'), 'auction_lots', ['object_type'], unique=False)
    op.create_index(op.f('ix_auction_lots_region'), 'auction_lots', ['region'], unique=False)
    op.create_index(op.f('ix_auction_lots_seller_bin'), 'auction_lots', ['seller_bin'], unique=False)
    op.create_index(op.f('ix_auction_lots_source'), 'auction_lots', ['source'], unique=False)
    op.create_index(op.f('ix_auction_lots_source_lot_id'), 'auction_lots', ['source_lot_id'], unique=False)
    op.create_index(op.f('ix_auction_lots_source_search_status'), 'auction_lots', ['source_search_status'], unique=False)
    op.create_index(op.f('ix_auction_lots_start_price_kzt'), 'auction_lots', ['start_price_kzt'], unique=False)
    op.create_index(op.f('ix_auction_lots_status'), 'auction_lots', ['status'], unique=False)
    op.create_table('feedback_broadcasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('ru_text', sa.Text(), nullable=False),
    sa.Column('kz_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('responded_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funnel_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('funnel_version', sa.String(length=8), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('funnel_session_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_events_event_name'), 'funnel_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_funnel_events_funnel_session_id'), 'funnel_events', ['funnel_session_id'], unique=False)
    op.create_index(op.f('ix_funnel_events_funnel_version'), 'funnel_events', ['funnel_version'], unique=False)
    op.create_index(op.f('ix_funnel_events_request_id'), 'funnel_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_funnel_events_telegram_user_id'), 'funnel_events', ['telegram_user_id'], unique=False)
    op.create_table('urban_plan_coverage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=160), nullable=False),
    sa.Column('locality', sa.String(length=160), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('coverage_status', sa.String(length=32), nullable=False),
    sa.Column('approved_layer_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'district', 'locality', 'purpose', name='uq_urban_plan_coverage_scope')
    )
    op.create_index(op.f('ix_urban_plan_coverage_coverage_status'), 'urban_plan_coverage', ['coverage_status'], unique=False)
    op.create_index(op.f('ix_urban_plan_coverage_district'), 'urban_plan_coverage', ['district'], unique=False)
    op.create_index(op.f('ix_urban_plan_coverage_locality'), 'urban_plan_coverage', ['locality'], unique=False)
    op.create_index(op.f('ix_urban_plan_coverage_purpose'), 'urban_plan_coverage', ['purpose'], unique=False)
    op.create_index(op.f('ix_urban_plan_coverage_region'), 'urban_plan_coverage', ['region'], unique=False)
    op.create_table('urban_plan_layers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=160), nullable=False),
    sa.Column('locality', sa.String(length=160), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('layer_kind', sa.String(length=32), nullable=False),
    sa.Column('zone_name', sa.String(length=240), nullable=True),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('approval_document', sa.String(length=320), nullable=False),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('source_authority', sa.String(length=240), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_epsg', sa.Integer(), nullable=False),
    sa.Column('source_file_name', sa.String(length=260), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_version', sa.String(length=120), nullable=True),
    sa.Column('provenance_status', sa.String(length=64), nullable=False),
    sa.Column('identity_status', sa.String(length=64), nullable=False),
    sa.Column('qa_status', sa.String(length=32), nullable=False),
    sa.Column('independent_review', sa.Boolean(), nullable=False),
    sa.Column('qa_review_json', sa.Text(), nullable=True),
    sa.Column('approved_for_search', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urban_plan_layers_active'), 'urban_plan_layers', ['active'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_approved_for_search'), 'urban_plan_layers', ['approved_for_search'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_district'), 'urban_plan_layers', ['district'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_identity_status'), 'urban_plan_layers', ['identity_status'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_layer_kind'), 'urban_plan_layers', ['layer_kind'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_locality'), 'urban_plan_layers', ['locality'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_provenance_status'), 'urban_plan_layers', ['provenance_status'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_purpose'), 'urban_plan_layers', ['purpose'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_qa_status'), 'urban_plan_layers', ['qa_status'], unique=False)
    op.create_index(op.f('ix_urban_plan_layers_region'), 'urban_plan_layers', ['region'], unique=False)
    op.create_table('urban_plan_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=160), nullable=False),
    sa.Column('locality', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('approval_document', sa.String(length=320), nullable=False),
    sa.Column('approval_date', sa.String(length=32), nullable=False),
    sa.Column('source_authority', sa.String(length=240), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('api_base_url', sa.Text(), nullable=False),
    sa.Column('admterr_id', sa.String(length=120), nullable=False),
    sa.Column('profiles_json', sa.Text(), nullable=True),
    sa.Column('collections_json', sa.Text(), nullable=True),
    sa.Column('coverage_status', sa.String(length=32), nullable=False),
    sa.Column('import_status', sa.String(length=32), nullable=False),
    sa.Column('layer_count', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_urban_plan_source_platform_external')
    )
    op.create_index(op.f('ix_urban_plan_sources_coverage_status'), 'urban_plan_sources', ['coverage_status'], unique=False)
    op.create_index(op.f('ix_urban_plan_sources_district'), 'urban_plan_sources', ['district'], unique=False)
    op.create_index(op.f('ix_urban_plan_sources_import_status'), 'urban_plan_sources', ['import_status'], unique=False)
    op.create_index(op.f('ix_urban_plan_sources_locality'), 'urban_plan_sources', ['locality'], unique=False)
    op.create_index(op.f('ix_urban_plan_sources_platform'), 'urban_plan_sources', ['platform'], unique=False)
    op.create_index(op.f('ix_urban_plan_sources_region'), 'urban_plan_sources', ['region'], unique=False)
    op.create_index(op.f('ix_urban_plan_sources_source_type'), 'urban_plan_sources', ['source_type'], unique=False)
    op.create_table('web_login_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('password_hash', sa.String(length=220), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_login_codes_expires_at'), 'web_login_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_web_login_codes_phone'), 'web_login_codes', ['phone'], unique=False)
    op.create_table('account_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('payment_amount_kzt', sa.Integer(), nullable=True),
    sa.Column('payment_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('payment_provider', sa.String(length=32), nullable=True),
    sa.Column('payment_provider_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('payment_provider_status', sa.String(length=32), nullable=True),
    sa.Column('payment_provider_url', sa.Text(), nullable=True),
    sa.Column('payment_provider_qr_image_url', sa.Text(), nullable=True),
    sa.Column('payment_provider_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_payments_account_id'), 'account_payments', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_payments_payment_provider_invoice_id'), 'account_payments', ['payment_provider_invoice_id'], unique=False)
    op.create_index(op.f('ix_account_payments_payment_status'), 'account_payments', ['payment_status'], unique=False)
    op.create_table('auction_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('free_lot_id', sa.String(length=36), nullable=True),
    sa.Column('paid_access', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('payment_amount_kzt', sa.Integer(), nullable=True),
    sa.Column('payment_provider', sa.String(length=32), nullable=True),
    sa.Column('payment_provider_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('payment_provider_status', sa.String(length=32), nullable=True),
    sa.Column('payment_provider_url', sa.Text(), nullable=True),
    sa.Column('payment_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_provider_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_confirmation_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['free_lot_id'], ['auction_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_access_access_expires_at'), 'auction_access', ['access_expires_at'], unique=False)
    op.create_index(op.f('ix_auction_access_free_lot_id'), 'auction_access', ['free_lot_id'], unique=False)
    op.create_index(op.f('ix_auction_access_paid_access'), 'auction_access', ['paid_access'], unique=False)
    op.create_index(op.f('ix_auction_access_payment_provider_invoice_id'), 'auction_access', ['payment_provider_invoice_id'], unique=True)
    op.create_index(op.f('ix_auction_access_payment_status'), 'auction_access', ['payment_status'], unique=False)
    op.create_index(op.f('ix_auction_access_telegram_user_id'), 'auction_access', ['telegram_user_id'], unique=True)
    op.create_table('auction_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=320), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'source_url', name='uq_auction_document_lot_url')
    )
    op.create_index(op.f('ix_auction_documents_lot_id'), 'auction_documents', ['lot_id'], unique=False)
    op.create_table('auction_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'lot_id', name='uq_auction_favorite_account_lot'),
    sa.UniqueConstraint('telegram_user_id', 'lot_id', name='uq_auction_favorite_user_lot')
    )
    op.create_index(op.f('ix_auction_favorites_account_id'), 'auction_favorites', ['account_id'], unique=False)
    op.create_index(op.f('ix_auction_favorites_lot_id'), 'auction_favorites', ['lot_id'], unique=False)
    op.create_index(op.f('ix_auction_favorites_telegram_user_id'), 'auction_favorites', ['telegram_user_id'], unique=False)
    op.create_table('auction_lot_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_lot_changes_changed_at'), 'auction_lot_changes', ['changed_at'], unique=False)
    op.create_index(op.f('ix_auction_lot_changes_field_name'), 'auction_lot_changes', ['field_name'], unique=False)
    op.create_index(op.f('ix_auction_lot_changes_lot_id'), 'auction_lot_changes', ['lot_id'], unique=False)
    op.create_table('auction_lot_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('start_price_kzt', sa.Float(), nullable=True),
    sa.Column('sale_price_kzt', sa.Float(), nullable=True),
    sa.Column('auction_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_lot_history_lot_id'), 'auction_lot_history', ['lot_id'], unique=False)
    op.create_index(op.f('ix_auction_lot_history_status'), 'auction_lot_history', ['status'], unique=False)
    op.create_table('auction_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=160), nullable=True),
    sa.Column('district', sa.String(length=160), nullable=True),
    sa.Column('locality', sa.String(length=160), nullable=True),
    sa.Column('purpose_query', sa.String(length=160), nullable=True),
    sa.Column('min_price_kzt', sa.Float(), nullable=True),
    sa.Column('max_price_kzt', sa.Float(), nullable=True),
    sa.Column('min_area_ha', sa.Float(), nullable=True),
    sa.Column('max_area_ha', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id', 'region', 'district', 'locality', 'purpose_query', 'min_price_kzt', 'max_price_kzt', 'min_area_ha', 'max_area_ha', name='uq_auction_subscription_filter_v2')
    )
    op.create_index(op.f('ix_auction_subscriptions_account_id'), 'auction_subscriptions', ['account_id'], unique=False)
    op.create_index(op.f('ix_auction_subscriptions_active'), 'auction_subscriptions', ['active'], unique=False)
    op.create_index(op.f('ix_auction_subscriptions_district'), 'auction_subscriptions', ['district'], unique=False)
    op.create_index(op.f('ix_auction_subscriptions_locality'), 'auction_subscriptions', ['locality'], unique=False)
    op.create_index(op.f('ix_auction_subscriptions_region'), 'auction_subscriptions', ['region'], unique=False)
    op.create_index(op.f('ix_auction_subscriptions_telegram_chat_id'), 'auction_subscriptions', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_auction_subscriptions_telegram_user_id'), 'auction_subscriptions', ['telegram_user_id'], unique=False)
    op.create_table('feedback_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_client_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_admin_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_conversations_account_id'), 'feedback_conversations', ['account_id'], unique=False)
    op.create_index(op.f('ix_feedback_conversations_language'), 'feedback_conversations', ['language'], unique=False)
    op.create_index(op.f('ix_feedback_conversations_last_message_at'), 'feedback_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_feedback_conversations_phone'), 'feedback_conversations', ['phone'], unique=False)
    op.create_index(op.f('ix_feedback_conversations_status'), 'feedback_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_conversations_telegram_chat_id'), 'feedback_conversations', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_feedback_conversations_telegram_user_id'), 'feedback_conversations', ['telegram_user_id'], unique=False)
    op.create_table('search_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('web_account_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=True),
    sa.Column('funnel_session_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=160), nullable=False),
    sa.Column('region_label', sa.String(length=160), nullable=True),
    sa.Column('district', sa.String(length=160), nullable=False),
    sa.Column('district_label', sa.String(length=160), nullable=True),
    sa.Column('locality', sa.String(length=160), nullable=True),
    sa.Column('locality_label', sa.String(length=160), nullable=True),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('allotment_type', sa.String(length=32), nullable=True),
    sa.Column('irrigation_type', sa.String(length=32), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.Column('result_limit', sa.Integer(), nullable=False),
    sa.Column('cemetery_buffer_m', sa.Integer(), nullable=False),
    sa.Column('max_road_distance_m', sa.Integer(), nullable=False),
    sa.Column('max_power_distance_m', sa.Integer(), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=True),
    sa.Column('retry_of_request_id', sa.String(length=36), nullable=True),
    sa.Column('continuation_of_request_id', sa.String(length=36), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('terms_version', sa.String(length=32), nullable=True),
    sa.Column('terms_text_snapshot', sa.Text(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('progress_message_id', sa.Integer(), nullable=True),
    sa.Column('search_completed_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_outcome', sa.String(length=48), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('urban_plan_status', sa.String(length=32), nullable=False),
    sa.Column('urban_plan_message', sa.Text(), nullable=True),
    sa.Column('urban_plan_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('urban_plan_override_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('urban_plan_override_user_id', sa.String(length=32), nullable=True),
    sa.Column('urban_plan_override_text', sa.Text(), nullable=True),
    sa.Column('urban_plan_waiver_kind', sa.String(length=32), nullable=True),
    sa.Column('urban_plan_auto_waive_reason', sa.Text(), nullable=True),
    sa.Column('urban_plan_coverage_status', sa.String(length=32), nullable=True),
    sa.Column('urban_plan_coverage_id', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('payment_amount_kzt', sa.Integer(), nullable=True),
    sa.Column('payment_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('payment_confirmation_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_provider', sa.String(length=32), nullable=True),
    sa.Column('payment_provider_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('payment_provider_status', sa.String(length=32), nullable=True),
    sa.Column('payment_provider_url', sa.Text(), nullable=True),
    sa.Column('payment_provider_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('free_preview_status', sa.String(length=32), nullable=False),
    sa.Column('free_preview_count', sa.Integer(), nullable=False),
    sa.Column('free_preview_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('free_preview_approved_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['web_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_requests_access_expires_at'), 'search_requests', ['access_expires_at'], unique=False)
    op.create_index(op.f('ix_search_requests_continuation_of_request_id'), 'search_requests', ['continuation_of_request_id'], unique=False)
    op.create_index(op.f('ix_search_requests_district'), 'search_requests', ['district'], unique=False)
    op.create_index(op.f('ix_search_requests_free_preview_status'), 'search_requests', ['free_preview_status'], unique=False)
    op.create_index(op.f('ix_search_requests_funnel_session_id'), 'search_requests', ['funnel_session_id'], unique=False)
    op.create_index(op.f('ix_search_requests_payment_provider_invoice_id'), 'search_requests', ['payment_provider_invoice_id'], unique=False)
    op.create_index(op.f('ix_search_requests_payment_status'), 'search_requests', ['payment_status'], unique=False)
    op.create_index(op.f('ix_search_requests_retry_of_request_id'), 'search_requests', ['retry_of_request_id'], unique=False)
    op.create_index(op.f('ix_search_requests_search_outcome'), 'search_requests', ['search_outcome'], unique=False)
    op.create_index(op.f('ix_search_requests_status'), 'search_requests', ['status'], unique=False)
    op.create_index(op.f('ix_search_requests_telegram_user_id'), 'search_requests', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_search_requests_urban_plan_coverage_status'), 'search_requests', ['urban_plan_coverage_status'], unique=False)
    op.create_index(op.f('ix_search_requests_urban_plan_status'), 'search_requests', ['urban_plan_status'], unique=False)
    op.create_index(op.f('ix_search_requests_web_account_id'), 'search_requests', ['web_account_id'], unique=False)
    op.create_table('telegram_link_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_link_tokens_account_id'), 'telegram_link_tokens', ['account_id'], unique=False)
    op.create_index(op.f('ix_telegram_link_tokens_expires_at'), 'telegram_link_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_telegram_link_tokens_telegram_user_id'), 'telegram_link_tokens', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_telegram_link_tokens_token_hash'), 'telegram_link_tokens', ['token_hash'], unique=True)
    op.create_table('web_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_sessions_account_id'), 'web_sessions', ['account_id'], unique=False)
    op.create_index(op.f('ix_web_sessions_expires_at'), 'web_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_web_sessions_token_hash'), 'web_sessions', ['token_hash'], unique=True)
    op.create_table('auction_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['auction_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'lot_id', name='uq_auction_notification_lot')
    )
    op.create_index(op.f('ix_auction_notifications_lot_id'), 'auction_notifications', ['lot_id'], unique=False)
    op.create_index(op.f('ix_auction_notifications_subscription_id'), 'auction_notifications', ['subscription_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('region_chain', sa.String(length=260), nullable=False),
    sa.Column('locality', sa.String(length=180), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('nearby_cadastre', sa.String(length=32), nullable=False),
    sa.Column('nearby_distance_m', sa.Float(), nullable=True),
    sa.Column('nearby_land_use', sa.String(length=240), nullable=True),
    sa.Column('nearby_category_id', sa.String(length=16), nullable=True),
    sa.Column('requested_area_ha', sa.Float(), nullable=False),
    sa.Column('road_distance_m', sa.Float(), nullable=True),
    sa.Column('power_evidence', sa.Text(), nullable=False),
    sa.Column('water_evidence', sa.Text(), nullable=False),
    sa.Column('sewer_evidence', sa.Text(), nullable=False),
    sa.Column('cemetery_distance_m', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=False),
    sa.Column('google_maps_url', sa.Text(), nullable=False),
    sa.Column('egkn_url', sa.Text(), nullable=False),
    sa.Column('source_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('google_checked', sa.Boolean(), nullable=False),
    sa.Column('google_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer', sa.String(length=120), nullable=True),
    sa.Column('urban_plan_status', sa.String(length=32), nullable=False),
    sa.Column('urban_plan_zone', sa.String(length=240), nullable=True),
    sa.Column('urban_plan_document', sa.String(length=320), nullable=True),
    sa.Column('urban_plan_source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['search_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_delivered_at'), 'candidates', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_candidates_nearby_cadastre'), 'candidates', ['nearby_cadastre'], unique=False)
    op.create_index(op.f('ix_candidates_request_id'), 'candidates', ['request_id'], unique=False)
    op.create_index(op.f('ix_candidates_urban_plan_status'), 'candidates', ['urban_plan_status'], unique=False)
    op.create_table('feedback_broadcast_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broadcast_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['broadcast_id'], ['feedback_broadcasts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['feedback_conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'telegram_user_id', name='uq_feedback_broadcast_user')
    )
    op.create_index(op.f('ix_feedback_broadcast_recipients_account_id'), 'feedback_broadcast_recipients', ['account_id'], unique=False)
    op.create_index(op.f('ix_feedback_broadcast_recipients_broadcast_id'), 'feedback_broadcast_recipients', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_feedback_broadcast_recipients_conversation_id'), 'feedback_broadcast_recipients', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feedback_broadcast_recipients_language'), 'feedback_broadcast_recipients', ['language'], unique=False)
    op.create_index(op.f('ix_feedback_broadcast_recipients_responded_at'), 'feedback_broadcast_recipients', ['responded_at'], unique=False)
    op.create_index(op.f('ix_feedback_broadcast_recipients_sent_at'), 'feedback_broadcast_recipients', ['sent_at'], unique=False)
    op.create_index(op.f('ix_feedback_broadcast_recipients_status'), 'feedback_broadcast_recipients', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_broadcast_recipients_telegram_chat_id'), 'feedback_broadcast_recipients', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_feedback_broadcast_recipients_telegram_user_id'), 'feedback_broadcast_recipients', ['telegram_user_id'], unique=False)
    op.create_table('feedback_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('broadcast_id', sa.String(length=36), nullable=True),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('delivery_status', sa.String(length=24), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['feedback_broadcasts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['feedback_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_messages_broadcast_id'), 'feedback_messages', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_feedback_messages_channel'), 'feedback_messages', ['channel'], unique=False)
    op.create_index(op.f('ix_feedback_messages_conversation_id'), 'feedback_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feedback_messages_delivery_status'), 'feedback_messages', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_feedback_messages_sender_type'), 'feedback_messages', ['sender_type'], unique=False)
    op.create_index('ix_search_requests_status_updated_at', 'search_requests', ['status', 'updated_at'], unique=False)
    op.create_index('ix_search_requests_payment_status_user', 'search_requests', ['payment_status', 'telegram_user_id'], unique=False)
    op.create_index('ix_search_requests_payment_status_account', 'search_requests', ['payment_status', 'web_account_id'], unique=False)
    op.create_index('ix_search_requests_funnel_session_status', 'search_requests', ['funnel_session_id', 'status'], unique=False)
    op.create_index('ix_account_payments_status_account_created', 'account_payments', ['payment_status', 'account_id', 'created_at'], unique=False)
    op.create_index('ix_web_sessions_account_active', 'web_sessions', ['account_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index('ix_auction_lots_active_region_district_start', 'auction_lots', ['active', 'region', 'district', 'auction_starts_at'], unique=False)
    op.create_index('ix_auction_subscriptions_active_region_district', 'auction_subscriptions', ['active', 'region', 'district', 'locality'], unique=False)
    op.create_index('ix_search_requests_retry_of_request_id_unique', 'search_requests', ['retry_of_request_id'], unique=True, postgresql_where=sa.text('retry_of_request_id IS NOT NULL'), sqlite_where=sa.text('retry_of_request_id IS NOT NULL'))
    op.create_index('ix_search_requests_continuation_unique', 'search_requests', ['continuation_of_request_id'], unique=True, postgresql_where=sa.text('continuation_of_request_id IS NOT NULL'), sqlite_where=sa.text('continuation_of_request_id IS NOT NULL'))
    op.create_index('ix_search_requests_payment_provider_invoice_unique', 'search_requests', ['payment_provider', 'payment_provider_invoice_id'], unique=True, postgresql_where=sa.text('payment_provider IS NOT NULL AND payment_provider_invoice_id IS NOT NULL'), sqlite_where=sa.text('payment_provider IS NOT NULL AND payment_provider_invoice_id IS NOT NULL'))
    op.create_index('ix_account_payments_provider_invoice_unique', 'account_payments', ['payment_provider', 'payment_provider_invoice_id'], unique=True, postgresql_where=sa.text('payment_provider IS NOT NULL AND payment_provider_invoice_id IS NOT NULL'), sqlite_where=sa.text('payment_provider IS NOT NULL AND payment_provider_invoice_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_payments_provider_invoice_unique', table_name='account_payments')
    op.drop_index('ix_search_requests_payment_provider_invoice_unique', table_name='search_requests')
    op.drop_index('ix_search_requests_continuation_unique', table_name='search_requests')
    op.drop_index('ix_search_requests_retry_of_request_id_unique', table_name='search_requests')
    op.drop_index('ix_auction_subscriptions_active_region_district', table_name='auction_subscriptions')
    op.drop_index('ix_auction_lots_active_region_district_start', table_name='auction_lots')
    op.drop_index('ix_web_sessions_account_active', table_name='web_sessions')
    op.drop_index('ix_account_payments_status_account_created', table_name='account_payments')
    op.drop_index('ix_search_requests_funnel_session_status', table_name='search_requests')
    op.drop_index('ix_search_requests_payment_status_account', table_name='search_requests')
    op.drop_index('ix_search_requests_payment_status_user', table_name='search_requests')
    op.drop_index('ix_search_requests_status_updated_at', table_name='search_requests')
    op.drop_index(op.f('ix_feedback_messages_sender_type'), table_name='feedback_messages')
    op.drop_index(op.f('ix_feedback_messages_delivery_status'), table_name='feedback_messages')
    op.drop_index(op.f('ix_feedback_messages_conversation_id'), table_name='feedback_messages')
    op.drop_index(op.f('ix_feedback_messages_channel'), table_name='feedback_messages')
    op.drop_index(op.f('ix_feedback_messages_broadcast_id'), table_name='feedback_messages')
    op.drop_table('feedback_messages')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_telegram_user_id'), table_name='feedback_broadcast_recipients')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_telegram_chat_id'), table_name='feedback_broadcast_recipients')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_status'), table_name='feedback_broadcast_recipients')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_sent_at'), table_name='feedback_broadcast_recipients')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_responded_at'), table_name='feedback_broadcast_recipients')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_language'), table_name='feedback_broadcast_recipients')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_conversation_id'), table_name='feedback_broadcast_recipients')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_broadcast_id'), table_name='feedback_broadcast_recipients')
    op.drop_index(op.f('ix_feedback_broadcast_recipients_account_id'), table_name='feedback_broadcast_recipients')
    op.drop_table('feedback_broadcast_recipients')
    op.drop_index(op.f('ix_candidates_urban_plan_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_request_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_nearby_cadastre'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_delivered_at'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_auction_notifications_subscription_id'), table_name='auction_notifications')
    op.drop_index(op.f('ix_auction_notifications_lot_id'), table_name='auction_notifications')
    op.drop_table('auction_notifications')
    op.drop_index(op.f('ix_web_sessions_token_hash'), table_name='web_sessions')
    op.drop_index(op.f('ix_web_sessions_expires_at'), table_name='web_sessions')
    op.drop_index(op.f('ix_web_sessions_account_id'), table_name='web_sessions')
    op.drop_table('web_sessions')
    op.drop_index(op.f('ix_telegram_link_tokens_token_hash'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_telegram_user_id'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_expires_at'), table_name='telegram_link_tokens')
    op.drop_index(op.f('ix_telegram_link_tokens_account_id'), table_name='telegram_link_tokens')
    op.drop_table('telegram_link_tokens')
    op.drop_index(op.f('ix_search_requests_web_account_id'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_urban_plan_status'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_urban_plan_coverage_status'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_telegram_user_id'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_status'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_search_outcome'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_retry_of_request_id'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_payment_status'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_payment_provider_invoice_id'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_funnel_session_id'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_free_preview_status'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_district'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_continuation_of_request_id'), table_name='search_requests')
    op.drop_index(op.f('ix_search_requests_access_expires_at'), table_name='search_requests')
    op.drop_table('search_requests')
    op.drop_index(op.f('ix_feedback_conversations_telegram_user_id'), table_name='feedback_conversations')
    op.drop_index(op.f('ix_feedback_conversations_telegram_chat_id'), table_name='feedback_conversations')
    op.drop_index(op.f('ix_feedback_conversations_status'), table_name='feedback_conversations')
    op.drop_index(op.f('ix_feedback_conversations_phone'), table_name='feedback_conversations')
    op.drop_index(op.f('ix_feedback_conversations_last_message_at'), table_name='feedback_conversations')
    op.drop_index(op.f('ix_feedback_conversations_language'), table_name='feedback_conversations')
    op.drop_index(op.f('ix_feedback_conversations_account_id'), table_name='feedback_conversations')
    op.drop_table('feedback_conversations')
    op.drop_index(op.f('ix_auction_subscriptions_telegram_user_id'), table_name='auction_subscriptions')
    op.drop_index(op.f('ix_auction_subscriptions_telegram_chat_id'), table_name='auction_subscriptions')
    op.drop_index(op.f('ix_auction_subscriptions_region'), table_name='auction_subscriptions')
    op.drop_index(op.f('ix_auction_subscriptions_locality'), table_name='auction_subscriptions')
    op.drop_index(op.f('ix_auction_subscriptions_district'), table_name='auction_subscriptions')
    op.drop_index(op.f('ix_auction_subscriptions_active'), table_name='auction_subscriptions')
    op.drop_index(op.f('ix_auction_subscriptions_account_id'), table_name='auction_subscriptions')
    op.drop_table('auction_subscriptions')
    op.drop_index(op.f('ix_auction_lot_history_status'), table_name='auction_lot_history')
    op.drop_index(op.f('ix_auction_lot_history_lot_id'), table_name='auction_lot_history')
    op.drop_table('auction_lot_history')
    op.drop_index(op.f('ix_auction_lot_changes_lot_id'), table_name='auction_lot_changes')
    op.drop_index(op.f('ix_auction_lot_changes_field_name'), table_name='auction_lot_changes')
    op.drop_index(op.f('ix_auction_lot_changes_changed_at'), table_name='auction_lot_changes')
    op.drop_table('auction_lot_changes')
    op.drop_index(op.f('ix_auction_favorites_telegram_user_id'), table_name='auction_favorites')
    op.drop_index(op.f('ix_auction_favorites_lot_id'), table_name='auction_favorites')
    op.drop_index(op.f('ix_auction_favorites_account_id'), table_name='auction_favorites')
    op.drop_table('auction_favorites')
    op.drop_index(op.f('ix_auction_documents_lot_id'), table_name='auction_documents')
    op.drop_table('auction_documents')
    op.drop_index(op.f('ix_auction_access_telegram_user_id'), table_name='auction_access')
    op.drop_index(op.f('ix_auction_access_payment_status'), table_name='auction_access')
    op.drop_index(op.f('ix_auction_access_payment_provider_invoice_id'), table_name='auction_access')
    op.drop_index(op.f('ix_auction_access_paid_access'), table_name='auction_access')
    op.drop_index(op.f('ix_auction_access_free_lot_id'), table_name='auction_access')
    op.drop_index(op.f('ix_auction_access_access_expires_at'), table_name='auction_access')
    op.drop_table('auction_access')
    op.drop_index(op.f('ix_account_payments_payment_status'), table_name='account_payments')
    op.drop_index(op.f('ix_account_payments_payment_provider_invoice_id'), table_name='account_payments')
    op.drop_index(op.f('ix_account_payments_account_id'), table_name='account_payments')
    op.drop_table('account_payments')
    op.drop_index(op.f('ix_web_login_codes_phone'), table_name='web_login_codes')
    op.drop_index(op.f('ix_web_login_codes_expires_at'), table_name='web_login_codes')
    op.drop_table('web_login_codes')
    op.drop_index(op.f('ix_urban_plan_sources_source_type'), table_name='urban_plan_sources')
    op.drop_index(op.f('ix_urban_plan_sources_region'), table_name='urban_plan_sources')
    op.drop_index(op.f('ix_urban_plan_sources_platform'), table_name='urban_plan_sources')
    op.drop_index(op.f('ix_urban_plan_sources_locality'), table_name='urban_plan_sources')
    op.drop_index(op.f('ix_urban_plan_sources_import_status'), table_name='urban_plan_sources')
    op.drop_index(op.f('ix_urban_plan_sources_district'), table_name='urban_plan_sources')
    op.drop_index(op.f('ix_urban_plan_sources_coverage_status'), table_name='urban_plan_sources')
    op.drop_table('urban_plan_sources')
    op.drop_index(op.f('ix_urban_plan_layers_region'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_qa_status'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_purpose'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_provenance_status'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_locality'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_layer_kind'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_identity_status'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_district'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_approved_for_search'), table_name='urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_layers_active'), table_name='urban_plan_layers')
    op.drop_table('urban_plan_layers')
    op.drop_index(op.f('ix_urban_plan_coverage_region'), table_name='urban_plan_coverage')
    op.drop_index(op.f('ix_urban_plan_coverage_purpose'), table_name='urban_plan_coverage')
    op.drop_index(op.f('ix_urban_plan_coverage_locality'), table_name='urban_plan_coverage')
    op.drop_index(op.f('ix_urban_plan_coverage_district'), table_name='urban_plan_coverage')
    op.drop_index(op.f('ix_urban_plan_coverage_coverage_status'), table_name='urban_plan_coverage')
    op.drop_table('urban_plan_coverage')
    op.drop_index(op.f('ix_funnel_events_telegram_user_id'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_request_id'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_funnel_version'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_funnel_session_id'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_event_name'), table_name='funnel_events')
    op.drop_table('funnel_events')
    op.drop_table('feedback_broadcasts')
    op.drop_index(op.f('ix_auction_lots_status'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_start_price_kzt'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_source_search_status'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_source_lot_id'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_source'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_seller_bin'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_region'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_object_type'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_last_seen_at'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_functional_purpose_level2'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_district'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_cadastre_number'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_auction_starts_at'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_auction_number'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_area_ha'), table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_active'), table_name='auction_lots')
    op.drop_table('auction_lots')
    op.drop_index(op.f('ix_accounts_trial_expires_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_telegram_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_phone'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_paid_access'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_locked_until'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_access_expires_at'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
